name: '[Dependabot NuGet] Build .NET'

on:
  push:
    branches:
      - 'dependabot/nuget/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  NUGET_CERT_REVOCATION_MODE: offline

jobs:

  net-test:
    name: .NET tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
        dotnet-quality: ga

    - name: Restore NuGet packages
      run: dotnet restore --verbosity minimal

    - name: Run .NET tests
      run: dotnet test --configuration Release

  net-build:
    name: .NET build
    runs-on: ubuntu-latest
    needs: [ net-test ]

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
        dotnet-quality: ga

    - name: Restore NuGet packages
      run: dotnet restore --verbosity minimal

    - name: Publish package
      run: dotnet pack -o ./artifacts -c Release ./src/RobotsTxt/RobotsTxt.csproj
      working-directory: ./
